# Build Stage
FROM maven:3.9.5-openjdk-21-slim AS build
WORKDIR /dashboard
COPY pom.xml .
COPY src ./src
RUN mvn clean package -DskipTests

# Runtime Stage
FROM openjdk:21-jre-slim-buster
WORKDIR /app
COPY --from=build /dashboard/target/*.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]
